// Generated by https://quicktype.io

import { Participant } from "./participant";

export interface Address {
  alias: string;
  city: string;
  mainStreet: string;
  houseNumber: string;
  secondaryStreet: string;
  reference: string;
  contactName: string;
  contactPhone: string;
  participant: Participant;
  sector: null;
  deletedAt: null;
  id: number;
  isDeleted: boolean;
}
