// Generated by https://quicktype.io

import { OptionLabel } from './common';

export enum CourierTypes {
  'SERVIENTREGA' = 'SERVIENTREGA',
}

export const avaliableCouriers: OptionLabel[] = [
  {
    label: 'SERVIENTREGA',
    value: CourierTypes.SERVIENTREGA,
  },
];
