// Generated by https://quicktype.io

import { Program } from "./program";

export interface PositionData {
  data: Position[];
  meta: Meta;
}

export interface Position {
  id: number;
  name: string;
  maxPointsPerMonth: null;
  maxPoints: null;
  isEditing: boolean;
  isDeleted: boolean;
  deletedAt: null;
  program: Program;
}

export interface Meta {
  page: number;
  take: number;
  itemCount: number;
  pageCount: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
